apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qa-role
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "statefulsets", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "describe", "exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qa-role-binding
  namespace: staging
subjects:
- kind: User
  name: qa-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: qa-role
  apiGroup: rbac.authorization.k8s.io
