apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 8080  # Your application's port
    targetPort: 8080  # Your container's port
